beelaineo/spinellikilcollin.com

app/src/components/Text.tsx, app/src/views/Footer/Footer.tsx, app/src/views/Footer/styled.tsx, app/src/views/Navigation/Navigation.tsx, app/src/views/Navigation/NavigationInner.tsx, app/src/views/Navigation/styled.tsx
Started mocking up the navigation with static data
=> fix(app): mocking out the navigation for style

app/src/components/ContentBlock/HeroBlock.tsx, app/src/components/Layout/Containers.tsx, app/src/graphql/fragments/content.ts
Fixing the hero block for mobile 
@good-idea Do you think the block should be taller on tablet?
=> fix(app): hero block mobile

app/src/components/Accordion/styled.tsx, app/src/components/Cart.tsx, app/src/components/ContentBlock/ImageTextBlock.tsx, app/src/components/Layout/Containers.tsx, app/src/components/Text.tsx, app/src/theme/color.ts, app/src/views/ProductDetail/ProductDetail.tsx, app/src/views/ProductDetail/components/BuyButton.tsx, app/src/views/ProductDetail/components/ProductDetailFooter.tsx, app/src/views/ProductDetail/components/ProductDetailHeader.tsx, app/src/views/ProductDetail/components/ProductRelated.tsx, app/src/views/ProductDetail/components/ProductVariantSelector.tsx, app/src/views/ProductDetail/styled.tsx
* Working on image blocks for pdp page
* styling the carousel for the pdp page
=> Feat product detail

app/src/components/Layout/Flex.tsx, app/src/theme/font.ts, app/src/theme/mediaQueries.ts, app/src/views/ProductListing/ProductListingHeader.tsx, app/src/views/ProductListing/ProductThumbnail.tsx, app/src/views/ProductListing/query.ts, app/src/views/ProductListing/styled.tsx
- Added badges to the collection page
- Made the collection headers full width
- Added a background color to the collections view
- Increased the wrapper width
=> Feat collection view

app/src/components/Navigation/Navigation.tsx, app/src/components/Navigation/SearchButton.tsx, app/src/components/Navigation/styled.tsx, app/src/components/Search/SearchInput.tsx
Search icon in primary navigation toggles Search pane
=> feat: search button in nav

app/src/views/ProductDetail/components/ProductDetailFooter.tsx, app/src/views/ProductDetail/components/ProductImages.tsx, app/src/views/ProductDetail/styled.tsx
images flow beneath info accordion
=> fix(app): remove image carousels on product mobile

app/src/components/Forms/Forms/ContactForm.tsx, app/src/components/Forms/Forms/CustomizationForm.tsx, app/src/components/Forms/Forms/RingSizerForm.tsx, app/src/services/hubspot.ts
format phone field and remove rejected body fields (dialingCode, phoneCountryCode) to fix Hubspot form submission
=> fix(app): hubspot forms

app/pages/_app.tsx, app/src/components/CTA.tsx, app/src/components/ContentBlock/HeroBlock.tsx, app/src/components/RichText/RichText.tsx, app/src/graphql/fragments/content.ts, app/src/types/generated-shopify.ts, sanity/schemas/objects/shared.js
add `min-height: 400px` to Image > styled.Wrapper to fix sizing bug
=> fix(app): hero image wrapper height

app/src/providers/BambuserProvider/configureBambuser.ts, app/src/providers/BambuserProvider/setupProductData.ts
1. fix options bug in setupProductData.ts
2. make Bambuser cookies readable from checkout
=> fix(app): bambuser fixes

app/pages/_app.tsx
URL param `openChat=true` launches Hubspot chat
=> fix(app): rework openChat URL param action

app/src/providers/BambuserProvider/setupProductData.ts
setupProductData for products w/ no options (1 default variant)
=> fix(app): bambuser product setup

app/src/providers/AnalyticsProvider/AnalyticsProvider.tsx, app/src/types/globals.ts, app/src/utils/fpixel.ts
add a function that reports Add To Cart events to FB, deduplicate PageView events by adding EventID
=> fix(app): Facebook Conversions API

app/src/utils/product.tsx, app/src/views/ProductDetail/ProductDetail.tsx
=> fix(app): override variant titles for 'Gift Card' products

app/pages/_app.tsx
=> fix(app): add GTM script, remove google analytics/pinterest scripts

app/src/views/ProductDetail/ProductDetail.tsx, app/src/views/ProductDetail/components/ProductDetailHeader.tsx, app/src/views/ProductDetail/components/ProductImages.tsx, app/src/views/ProductDetail/styled.tsx
to bring range slider closer to pricing information (variant title)
=> fix(app): switch order of Title / Image on mobile Gift Cards

app/src/components/Navigation/Navigation.tsx, app/src/providers/NavigationProvider.tsx, app/src/views/Homepage/Homepage.tsx
on navigation or homepage unmount set navigation colortheme to default
=> fix(app): themed header cleanup function

app/src/data/redirects.json
=> fix(app): remove redundant product redirect

app/src/components/Product/ProductGrid.tsx, app/src/components/Product/ProductThumbnail.tsx, app/src/views/ProductListing/ProductListing.tsx
for collections with manually selected initial variants and hidden filters
=> fix(app): disable currentVariant updates if filter is hidden

app/pages/_app.tsx
=> fix(app): affirm script loading

app/pages/about/contact.tsx, app/src/types/generated-sanity.ts, app/src/types/generated-shopify.ts, app/src/views/ContactView/Contact.tsx, sanity/schemas/documents/contact.js
link contact page lines to sanity document
=> contact page fix

app/next.config.js, app/src/components/CloudinaryVideo/CloudinaryAnimation.tsx, app/src/components/Filter/reducer.ts, app/src/utils/product.tsx, app/src/views/ProductDetail/ProductDetail.tsx
=> fix(app): PDL render animations bug on mobile

app/src/components/Cart/Checkout.tsx
**Close cart on router update**: this closes the cart when selecting a product within the side cart overlay, and also using back or forward buttons.
=> feat(app): close cart on router update

.eslintrc.js, app/pages/about/[pageSlug].tsx, app/pages/collections/[collectionSlug].tsx, app/pages/index.tsx, app/pages/products/[productSlug].tsx, app/src/hooks/useRefetch.tsx
- Fixes preview url parameter on home page
https://goodidea.notion.site/Sanity-Previews-not-working-f4928b9ab9464fc79c829f66f0b4b6db
---
**Additionally:**
- Installs eslint-plugin-react-hooks, warns on on rules-of-hooks
- Fixes conditional hook warning on use of `useRefetch`
=> Fix homepage preview

app/src/components/Carousel/CollectionCarousel.tsx, app/src/components/Carousel/ItemsCarousel.tsx, app/src/components/Product/ProductThumbnail.tsx, app/src/components/Product/styled.ts
solves occasional bug on PDP with Carousel thumbnail formatting
=> fix(app): fix styling of VideoWrapper on ProductThumbs

app/src/views/ProductListing/ProductListing.tsx
even when there are inline collection blocks
=> fix(app): show PDL 404 when product results is zero

app/.babelrc.js, app/package.json, app/pages/_app.tsx, app/pages/collections/[collectionSlug].tsx, app/src/providers/AllProviders.tsx, app/src/views/ProductListing/ProductListing.tsx, app/src/views/ProductListing/ProductListingHeader.tsx, yarn.lock
- delete `keep-alive` cache when navigating to a new collection
- replace `react-activation` library with `react-next-keep-alive`...this utilizes `next/router` and fixes hydration errors on collection pages
=> fix(app): remove keep-alive cache on collection change

app/src/components/Accordion/Accordion.tsx, app/src/components/Accordion/styled.tsx
- On page load, auto-expands accordion description panel on product description page (3 second delay)
- Adds height transition to accordion
=> feat:(app) auto-expand accordion description on PDP

app/src/components/Carousel/CollectionCarousel.tsx, app/src/graphql/fragments/content.ts
- Moves carousel collection product request to page query
=> fix(app): carousel image loading

app/src/components/Product/ProductThumbnail.tsx
**Filter not populating the correct variant**
https://www.notion.so/goodidea/Filter-not-populating-the-correct-variant-89891aac66f3448daa2c2fb83300ca59?pvs=4
- Fixes logic set in https://github.com/beelaineo/spinellikilcollin.com/pull/226 that was preventing the variants by filter match to be selected
=> fix(app): filter not populating the correct variant

app/src/services/sentry.ts
Uses `ignoreErrors` instead of `beforeSend` to filter out hydration errors from Sentry
=> chore(app): fix ignoring of hydration errors

app/src/components/Product/ProductThumbnail.tsx
**Single product variant animation not playing**
https://www.notion.so/goodidea/Single-product-variant-animation-not-playing-7e956e0b7c1645aebf4c9ac71707ea86?pvs=4
- for single product variant animations, check for animation within the style option
=> fix(app): get single product variant animation from style option

app/src/components/CloudinaryVideo/styled.ts, app/src/components/RichText/RichText.tsx, app/src/providers/ShopDataProvider/ShopDataProvider.tsx, app/src/types/richtext.ts, app/src/utils/links.ts
**RichText Video Embeds and Internal Links bug**
https://goodidea.notion.site/RichText-Video-Embeds-and-Internal-Links-bug-82c2d8c5a0234a07b8f691ddbc9bf3b1
=> fix(app): fix internalLinks and Videos in RichText

app/src/components/Filter/Filter.tsx, app/src/components/Product/ProductSwatches.tsx, app/src/components/Product/ProductThumbnail.tsx, app/src/components/RichText/RichText.tsx, app/src/utils/links.ts, app/src/views/ProductDetail/ProductDetail.tsx, app/src/views/ProductDetail/components/ProductDetailHeader.tsx, app/src/views/ProductDetail/components/ProductOptionSelector.tsx, app/src/views/ProductListing/ProductListing.tsx
- using product exclusion list in siteSettings to better handle low inventory variants
=> fix(app): ready to ship indicators

app/src/services/postmark/postmark.ts
=> fix(app): prevent form submission emails with suspicious sender email

app/src/components/Filter/styled.ts
Fixes z-index on filter panel: when scrolling down collection page, filter panel is being hidden collection thumbnails
=> fix(app): increase filter z-index

app/src/components/Cart/CheckoutProduct.tsx, app/src/components/Forms/Forms/SizeConverterForm.tsx, app/src/components/Product/ProductThumbnail.tsx, app/src/views/ProductDetail/ProductDetail.tsx, app/src/views/ProductDetail/components/BuyButton.tsx
=> fix(app) re-enable product analytics

app/src/components/Footer/Breadcrumbs.tsx, app/src/components/Navigation/Navigation.tsx, app/src/components/Navigation/styled.tsx, app/src/views/ProductDetail/styled.tsx
- adds Breadcrumbs module to header (in addition to footer), excluding Homepage and PDL's
- fixes inaccurate crumb pathways
=> fix(app): add Breadcrumbs to header

app/src/components/CloudinaryVideo/CloudinaryVideo.tsx, app/src/components/Footer/Breadcrumbs.tsx, app/src/components/Forms/Forms/SizeConverterForm.tsx, app/src/services/hubspot.ts, app/src/utils/links.ts, app/src/utils/tiktokpixel.ts
to use unencoded ShopifyVariantIds for variant matching
=> fix(app): update tiktok pixel events

app/src/views/ProductListing/ProductListing.tsx
- uses search provider to hide filters bar when search page is open.
=> fix(app): hide filters bar on search page

app/src/components/Filter/Filter.tsx, app/src/components/Filter/reducer.ts
- checks for filter updates on every update to router.query
=> fix(app): allow query updates on router update

app/src/components/Accordion/Accordion.tsx
Add `shouldOpen` prop to toggle off auto open for `Accordion` description section on PDP
=> feat(app): remove auto open on accordion

app/next.config.js
=> feat(app): add wildcard redirect rule to vercel

app/src/views/ProductDetail/components/ProductOptionSelector.tsx
- disables "natural" stone option for 2 carat items
- additionally, initializes stone and size variant selection from url
test link: https://spinellikilcollin-git-feat-adjust-two-00bfc5-spinelli-kilcollin.vercel.app/products/euclid
test link loading selection from variant in url: https://spinellikilcollin-git-feat-adjust-two-00bfc5-spinelli-kilcollin.vercel.app/products/euclid?v=Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MTE3ODg3ODY3Mjk5NA%3D%3D
=> feat(app): limit stone option selections for two carat items

app/src/views/ProductDetail/ProductDetail.tsx, app/src/views/ProductDetail/components/ProductOptionSelector.tsx, app/src/views/ProductDetail/components/ProductVariantSelector.tsx
preview link with test product: https://spinellikilcollin-git-feat-hard-code-85ba60-spinelli-kilcollin.vercel.app/products/euclid-test-product
=> feat(app): hard code inquiry only for listed wedding styles

app/pages/about/appointments.tsx, app/pages/products/[productSlug].tsx, app/src/components/Cart/Checkout.tsx, app/src/components/Cart/CheckoutProduct.tsx, app/src/components/Filter/PriceRangeFilter.tsx, app/src/components/Forms/Forms/CustomerCareForm.tsx, app/src/components/Forms/Forms/VIPLoyaltyForm.tsx, app/src/components/Product/ProductThumbnail.tsx, app/src/providers/CountryProvider/reducer.ts, app/src/providers/ShopifyPriceProvider/ShopifyPriceProvider.tsx, app/src/providers/ShopifyProvider/useCheckout/useCheckout.ts, app/src/types/generated-sanity.ts, app/src/types/generated-shopify.ts, app/src/utils/useProductVariant.ts, app/src/views/ProductDetail/ProductDetail.tsx, app/src/views/ProductDetail/components/BuyButton.tsx, app/src/views/ProductDetail/components/ProductDetailFooter.tsx, sanity/resolveProductionUrl.ts, sanity/schemas/objects/product/productOptionValue.tsx
- content (image/text) blocks on product option values in sanity
- active swatch updates display of PDP contentAfter (if exists)
=> feat(app): PDP content display rules based on selected color/style

app/src/data/redirects.json
=> fix(app): add redirect rule for 'ring-sizing'

app/src/providers/CurrencyProvider/CurrencyProvider.tsx, app/src/providers/CurrencyProvider/reducer.ts
=> fix(app): remove exchangeRate prop from updateCurrency()

app/pages/api/handleRequest.ts, app/pages/api/handleWebhookRequest.ts, app/pages/api/productUpdate.ts, app/pages/api/shopifyWebhookProductUpdate.ts, app/pages/api/webhookProductUpdate.ts, app/pages/api/webhookRequestTypes.ts, app/pages/api/webhookSanityOps.ts
- addresses `inventoryQuantity` bug with Sanity Connect app, circumvents the app
=> fix(app): add shopify productUpdate webhook handler

app/package.json, app/src/components/RichText/RichText.tsx, app/src/types/richtext.ts, sanity/package.json, yarn.lock
**Migrating from @sanity/block-content-to-react to @portabletext/react:** https://github.com/portabletext/react-portabletext/blob/main/MIGRATING.md#migrating-from-sanityblock-content-to-react-to-portabletextreact
=> feat(app): rich-text migration to portable-text

app/pages/api/handleWebhookRequest.ts, app/pages/api/shopifyWebhookCollectionCreate.ts, app/pages/api/shopifyWebhookCollectionDelete.ts, app/pages/api/shopifyWebhookCollectionUpdate.ts, app/pages/api/shopifyWebhookProductCreate.ts, app/pages/api/shopifyWebhookProductDelete.ts, app/pages/api/webhookCollectionUpdate.ts, app/pages/api/webhookProductUpdate.ts, app/pages/api/webhookRequestTypes.ts
Sync handlers for:
- productDelete
- productCreate
- collectionCreate
- collectionUpdate
- collectionDelete
=> fix(app): add add'l shopify webhook sync handlers

app/src/views/ProductDetail/components/ProductDetailFooter.tsx
- fix findMatchinColorOption() to check for 'Style' options on ProductDetailFooter
- fixes bug where swatch-linked image assets weren't appearing when the option changed on PDPs
=> fix(app): selected swatch contentAfter bug
