beelaineo/spinellikilcollin.com

app/src/components/Accordion/styled.tsx
app/src/components/ContentBlock/ContentBlock.tsx
app/src/components/ContentBlock/ImageTextBlock.tsx
app/src/components/ContentBlock/ImageWithoutText.tsx
app/src/components/Layout/Containers.tsx
app/src/components/Layout/Flex.tsx
app/src/components/Text.tsx
app/src/views/ProductDetail/ProductDetail.tsx
app/src/views/ProductDetail/components/ProductDetailFooter.tsx
app/src/views/ProductDetail/components/ProductRelated.tsx
app/src/views/ProductDetail/components/ProductVariantSelector.tsx

- Adding variant images for the product detail page (this will need to be updated so its working properly but getting the details there)
- styled related headers
- re organizing some details of the page

fix(app): variant images from shopify and styling details accordion

---

app/src/components/ContentBlock/HeroBlock.tsx

remove `min-height: 400px` on HeroBlock>HeroWrapper to fix hero media wrapper sizing issues on mobile

fix(app): HeroBlock > HeroWrapper sizing

---

app/src/graphql/fragments/shopify.ts
app/src/views/ProductDetail/components/ProductVariantSelector.tsx

fix(app): hide VariantSelector on products with only one variant

---

sanity/schemas/documents/journal.js
sanity/schemas/structure.js

The `intent=...` resolver was choking on our **Journal (Main Page)** structure, because it was missing a `.child(S.editor(...))`. I suppose the resolver runs through all available panes to see if it matches the document from the `intent=...` and compares them - but it was getting stuck when there was nothing to compare for the journal page.
I initially though it was an issue with the usage `listenQuery`. It wasn't, but that was causing the same loading issues that you mentioned, so this just sticks Journal Entries into a second level in the studio:

fix(sanity): refactor journal pane to avoid weird listenQuery bug

---

app/package.json
app/src/providers/BambuserProvider/setupProductData.ts

the Bambuser component is not hydrating product variants with Carat options properly...
(you can see the error on production site (and this preview branch) when you click the bottom button that is supposed to load the associated product variants from the video in the modal component.

fix(app): accommodate carat options in variants in Bambuser component

---

app/src/components/Image/utils.ts

**issue:** “Sonny” and “7mm” search terms result in blank page…
https://www.notion.so/goodidea/Search-Errors-2eade84f80e8440281567ad895299b9d
---
The product "Custom Sonny for Hannah size 7.5 - 50% payment" seems to be missing an image (see below), resulting in errors on search. This adds an additional check against undefined images.

fix(app): additional check on undefined images

---

app/src/components/Product/ProductThumbnail.tsx

This fixes carousel drag interactions on desktop by disabling the draggable state for the ProductThumbnail link. Previously on desktop, drag interaction for carousel was only working correctly if you clicked in-between the carousel elements.

fix(app): Disable draggable state for ProductThumbnail link

---

app/src/components/Filter/Filter.tsx
app/src/components/Product/ProductSwatches.tsx
app/src/components/Product/ProductThumbnail.tsx
app/src/views/ProductDetail/ProductDetail.tsx
app/src/views/ProductDetail/components/ProductDetailHeader.tsx

- hides inventory filter
- hides green `inStockDot`
- hides "Ready to Ship" headings
---
@beelaineo For now, I've commented out these features since we will be bringing them back soon. It would be good to make a quick pass on the site to make sure I got all of them. Also, we will want to remove "Shop In Stock" from the navigation in sanity.

feat:(app) hide in stock display and filter

---

app/pages/_app.tsx
app/src/components/Accordion/Accordion.tsx
app/src/components/Accordion/styled.tsx
app/src/components/RichText/RichText.tsx

**Info drawer container size**
https://goodidea.notion.site/Info-drawer-container-size-9e49db8c98c5414ab89b7a535b38e2f5
- accordion resizes on variant change
- fixes collision between onFocus and onClick events
---
**Text indentation error**
https://goodidea.notion.site/Text-indentation-error-b2c8198acbdd4607a4231275df598915
- regression from https://github.com/beelaineo/spinellikilcollin.com/pull/218, fixed on the mentioned elements
---
**Saved Scroll Position**
https://goodidea.notion.site/Saved-Scroll-Position-17bfcf5495a6428a8cf03ffe2ba7c6c7
- regression from https://github.com/beelaineo/spinellikilcollin.com/pull/218, previously added functionality to put element focus at the top of the page on route, though have disabled this for now since it was also removing scroll restoration.

fix(app): ui bug fixes

---

app/src/components/Carousel/CollectionCarousel.tsx

**“Rings” carousel at the bottom of product detail pages have disappeared**
https://goodidea.notion.site/Rings-carousel-at-the-bottom-of-product-detail-pages-have-disappeared-970b37c04c364cd6862246147b9ff5aa
- https://github.com/beelaineo/spinellikilcollin.com/pull/230 removed carousel query from `CollectionCarousel` and added products to the `CarouselFragment`, allowing products to load in during page request. This worked in most carousel uses but not where products within a collection were undefined and needed to be fetched. This PR adds back in the query to CollectionCarousel component, and only runs the request if products within a collection are not already defined.

fix(app): undefined products on related carousel

---

app/package.json
app/pages/api/algoliaIndex.ts
app/pages/api/sitemap.xml.tsx
app/pages/index.tsx
app/pages/products/[productSlug].tsx
app/src/graphql/request.ts
app/src/hooks/useSanityQuery/useSanityQuery.ts
app/src/providers/BambuserProvider/utils.ts
app/src/providers/CurrencyProvider/reducer.ts
app/src/providers/ErrorProvider/ErrorProvider.tsx
app/src/services/hubspot.ts
app/src/services/mailchimp/mailchimp.ts
app/src/services/postmark/postmark.ts
app/src/services/sentry.ts
app/src/services/webhooks.ts
yarn.lock

This improves the sentry setup by:
- Enforcing that `Sentry.captureException` is used with a tag, and makes passing in contextual data easier
- Ignores hydration errors. I believe that the issue is because we're using an older version of @xstyled/styled-components; (see #236) since these errors aren't really having a large impact (other than on our Sentry usage), I added a `beforeSend` param to sentry that (I believe) will filter these errors out.

feat(app): improve Sentry

---

sanity/package.json

I had a failing build because my `.env.local` was pointed to `staging`; it turns out the graphQL endpoint for that dataset is out of date.
This adds a separate script for deploying the latest schema to the `staging` endpoint. This won't be run with from `yarn deploy`, that will still:
- deploy the studio instance
- deploy the graphql endpoint for `production`
- re-generate types

chore(sanity): add deploy:graphql:staging script

---

app/src/utils/product.tsx

notion issue: https://www.notion.so/goodidea/Filter-not-populating-the-correct-variant-89891aac66f3448daa2c2fb83300ca59?pvs=4
Adds some additional variant selection overrides for some newer products:
- Sirius SG Pavé
- Acacia MX
- Jannsen

fix(app): add additional variant overrides for new products

---

app/src/components/Product/ProductGrid.tsx

**Tablet product carousel should crop double-wide blocks to square on Tablet Screen size (.925 Collection)**
https://www.notion.so/goodidea/Tablet-product-carousel-should-crop-double-wide-blocks-to-square-on-Tablet-Screen-size-925-Collect-0b723c83d8d846a58b3863705128d2df?pvs=4
- adds `featured` prop to `ProductGridItem`..., which adjusts the grid layout on tablet to keep the product and accompanying collection block on the same line. Since (I think) the only collection this currently is needed is on the .925 collection, it is being set only if `router.query.collectionSlug === '925-collection'`. If we end up using this format on other collections, it would be preferable to add it as an option in sanity. 
- removes commented out code

fix(app): adjust tablet layout of grid on .925 collection

---

app/src/components/Cart/CheckoutProduct.tsx
app/src/views/ProductDetail/components/ProductDetailHeader.tsx

**Strikethrough pricing in cart**
https://www.notion.so/goodidea/Strikethrough-pricing-in-cart-ad10f7341c304c65be0c384c6c11b8b3?pvs=4
- inside checkout, add strikethrough pricing for all products that have a `compareAtPriceV2` value
- test at: https://spinellikilcollin-git-feat-strike-thr-79dbf3-spinelli-kilcollin.vercel.app/collections/giaf

feat(app): add strike-through pricing to cart

---

app/pages/collections/[collectionSlug].tsx
app/src/graphql/fragments/content.ts

- moves `useRefetch` hook outside of conditional render
- fixes graphQL error (changes `FilterSetOrInventoryFilterOrPriceRangeFilter` to `FilterOrFilterSetOrInventoryFilterOrPriceRangeFilter` as per error's suggestion)

fix(app): collections preview

---

app/src/providers/AllProviders.tsx
app/src/views/ProductDetail/components/BuyButton.tsx

Adds a hook to query the Storefront API directly when rendering the Buy Button to ensure that the selected variant is in stock

feat(app): disable BuyButton until availableForSale is known

---

app/src/components/Cart/styled.tsx

Mobile Click Targets: https://www.notion.so/goodidea/Mobile-Click-Targets-c476cf20ffd140d9b650bff091c7adae?pvs=4
fixes click target size and position for `CheckoutProductCloseButton` (button to remove items from cart)

fix(app): align click target for CheckoutProductCloseButton

---

app/pages/api/onCollectionUpdate.ts
app/pages/api/onProductUpdate.ts

It turns out that the syncs are occasionally timing out - running for longer than 60 seconds. These weren't being caught by Sentry because vercel is just shutting down the function, nothing is being thrown (and then caught) by Sentry.
It appears that some products take a long time to sync. I'm not sure why, but the logs don't even include the product ID. This PR adds some additional logging info, and forces our own timeout (at 55 seconds) that we can catch & report to sentry.

chore(app): catch product/collection update sync timeouts

---

app/src/components/ContentBlock/HeroBlock.tsx
app/src/graphql/fragments/content.ts
app/src/types/generated-sanity.ts
sanity/schemas/objects/hero.js

In sanity, adds an option to turn on an extra-large font-size for hero heading text. This will be added to the hero panel on sanity, and is only enabled for H1 styled text. The font-size is dynamic, so it will resize with the page width. 
test link: https://spinellikilcollin-7m1m4efps-spinelli-kilcollin.vercel.app/about/test-julian
---

feat(sanity): add xl font size to hero heading

---

app/src/components/Affirm.tsx
app/src/views/ProductDetail/styled.tsx

- changes fixed span `height` to a fixed `min-height`
- changes width on desktop to `max-content` to prevent line-break
- aligns affirm content to left on mobile

fix(app): adjust affirm overlap

---

app/src/components/Search/SearchInput.tsx
app/vercel.json

- adds missing search params including `hideFromSearch:false` to query suggestion interface
- fixes algolia index refresh link by increasing server function timeout limit: https://vercel.com/docs/functions/configuring-functions/duration
---
test refresh link at: https://spinellikilcollin-git-fix-algolia-hid-b322d1-spinelli-kilcollin.vercel.app/api/algoliaIndex

fix(app): add hideFromSearch filter

---

app/src/components/Forms/Fields/ProductPriceInput.tsx
app/src/components/Forms/Form.tsx
app/src/views/ProductDetail/components/ProductOptionSelector.tsx
app/src/views/ProductDetail/components/ProductVariantSelector.tsx

- `ProductPriceInput` range slider values are populated variants, rather than equal steps. 
- On initial load, range slider initial position now matches variant value from query param. 
- Add `enableReinitialize` as prop to Form component (allows initial values to be reset)
test link: https://spinellikilcollin-git-feat-update-gif-5b6bec-spinelli-kilcollin.vercel.app/products/gift-card
test link with variant in url: https://spinellikilcollin-git-feat-update-gif-5b6bec-spinelli-kilcollin.vercel.app/products/gift-card?v=Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTQ4MjExNjE0NTI1MA%3D%3D

feat(app): update gift card range slider

---

app/pages/_app.tsx
app/src/components/Footer/Breadcrumbs.tsx
app/src/components/Footer/Footer.tsx
app/src/components/Navigation/Navigation.tsx
app/src/components/Search/SearchPane.tsx
app/src/hooks/useBreadcrumbs.tsx

- moves `breadCrumbs` data fetch to `useBreadcrumbs` hook in app folder, passes breadcrumb paths to nav and footer as props
- limits breadcrumb rerenders on variant change by changing useEffect dependency from `router.asPath` to `router.pathname`

feat(app): reduce breadcrumb queries

---

app/next.config.js
app/pages/_app.tsx
app/src/components/Product/ProductThumbnail.tsx
app/src/components/Product/styled.ts
app/src/providers/ShopifyPriceProvider/ShopifyPriceProvider.tsx

- adds caching for all static assets (fixes reloading of fonts): [4e0651b](https://github.com/beelaineo/spinellikilcollin.com/pull/366/commits/4e0651b9402a4372762f0d8c7699fae7553cf149)
- turn off optimistic client cache to prevent fetching data on link hover: https://github.com/vercel/next.js/discussions/40268
- changes thumbnail hover effect to fade in/out and not re-render on each hover interaction: [a32b720](https://github.com/beelaineo/spinellikilcollin.com/pull/366/commits/a32b7206f36a277594edb1e5e959336ea06b5e4f)
---
- reverts recently updated change to use `getVariantPriceById` back to `getVariantPriceByCollection.` There are a ton of requests for each item when loading in a collection, and this method should just do one request on page load. @beelaineo  could you see any reason …

feat(app): data optimizations

---

app/pages/api/algoliaIndex.ts
app/src/providers/SearchProvider/reducer.ts
app/src/providers/ShopifyPriceProvider/ShopifyPriceProvider.tsx

- fixes hidden us currency on search variants
- fixes search relevancy on certain terms...in this case, `bg` for "black gold" was being appended to the search term anytime the word black was used in the search, from previous settings to increase specificity. I've removed these appended matches since I don't think they are useful anymore with the current search settings, and also create issues with search terms such as `black diamonds`.

fix(app): search results bugs

---

app/src/utils/useProductVariant.ts
app/src/views/ProductDetail/ProductDetail.tsx

in some cases, product page data does not update properly when navigating forward and backward between products, crashing the page because of a mismatch between product and current variant data. In instances where page data is stale and the router has updated, this fix refreshes the router if `product.handle !== router.query.productSlug`.

fix(app): reload product page if data is stale on navigation

---

app/src/components/Filter/Filter.tsx

closes #381 
---
crashes on prod: https://www.spinellikilcollin.com/collections/best-sellers?utm_source=Google+Ads&utm_medium=Smart+Search&utm_campaign=Best+Sellers&gad_source=1&gbraid=0AAAAACU1zOjByZq08HTzOP_AKDgI913C6&gclid=CjwKCAjw4_K0BhBsEiwAfVVZ_4tCCXHrA5MM8MARJOjJYPrzHHEWW0DpDIdxYoe3_6GuarBOQuq6QhoC7AUQAvD_BwE,%20to:%20/collections/best-sellers?utm_source=Google+Ads&utm_medium=Smart+Search&utm_campaign=Best+Sellers&gad_source=1&gbraid=0AAAAACU1zOjByZq08HTzOP_AKDgI913C6&gclid=CjwKCAjw4_K0BhBsEiwAfVVZ_4tCCXHrA5MM8MARJOjJYPrzHHEWW0DpDIdxYoe3_6GuarBOQuq6QhoC7AUQAvD_BwE
fixed on preview: https://spinellikilcollin-git-fix-google-ads-504cf1-spinelli-kilcollin.vercel.app/collections/best-sellers?utm_source=Google+Ads&utm_medium=Smart+Search&utm_campaign=Best+Sellers&gad_source=1&gbraid=0AAAA …

fix(app): flatten ads query param with array

---

app/src/components/Accordion/Accordion.tsx

potential fix for #385 
---
- adds a debounce to resize-observer. this error doesn't seem to be breaking anything so we could also silence it by adding it to `ignoredErrors` in the sentry config.

fix(app): add debounce to resize-observer in accordion

---

app/src/views/ContactView/Contact.tsx
sanity/schemas/documents/contact.ts

adds two new additional line-types to contact page contact lines:
1. email
2. customer care - adds customer care modal link after contact line
---

feat(app): expand contact page functionality

---

app/src/components/RichText/RichText.tsx

- removes `listItem` from `RichText` components
- adds `textAction` to `RichText` components list, addresses warning in console: `Unknown mark type "textAction", please specify a serializer for it in the `serializers.marks` prop`

(fix): remove listItem from RichText component

---

app/src/components/Carousel/SuggestedProductsCarousel.tsx
app/src/views/ProductDetail/components/ProductRelated.tsx

- the carousel array of variants was showing up as empty instead of null on /anaka-earring, this additionally skips the custom collection if the array is empty.
- i noticed many of the carousel items, especially earrings, were repeating titles. this removes duplicates of a certain product if they do not differ in style or color.

fix(app): select preset collection if custom collection is empty

---

app/src/components/Carousel/SuggestedProductsCarousel.tsx
app/src/views/ProductDetail/components/ProductRelated.tsx

When a collection was not defined in sanity, the related products carousel was selecting the first collection listed on shopify. If this selected the rings collection, there is no way to limit the query size since its pulling in the whole collection. To fix this, if no collection is defined in sanity for the related products carousel, we are now pulling data from the product type and limiting the selection based on:
```
hideFromSearch: { neq: true }
archived: { neq: true }
hidden: { neq: true }
hideFromCollections: { neq: true }
```
Additionally, if the query becomes too large again, we can now limit the number of product matches for the query. For now I will leave it all products of a certain type since it is currently tested and working.

fix(app): fix large related products queries
